# All of the below functions are run during testing to make sure everything works as it should
# Currently we simply run 'cargo run tests' to run them all, in the future we'll make one actual test
# per command in order to not only test if the command executes, but also if the output is correct
[tests]
one = "echo hello"
two = ["echo hello", "echo again"]
three = { cmd = "ls", working_dir = "src" }
four = { cmd = "ls", working_dir = "./src" }
five = { cmd = ["ls", "ls"], working_dir = "./src" }
six = { cmd = ["echo we", "echo run", "echo in", "echo parallel"], parallel = true }
seven = { cmd = "print('Hello from python!')", shell = "python -c" }
eight = { cmd = "echo $MY_ENV", env = ["MY_ENV=Hello"] }
nine = { cmd = ["echo $MY_ENV"], env = ["MY_ENV=Hello"] }
ten = { cmd = "echo $ARG1 $ARG2", args = ["ARG1", "ARG2=Default value"] }
eleven = { cmd = "echo $MY_ENV $ARG1 $ARG2", env = ["MY_ENV=Dude"], args = ["ARG1", "ARG2=Default value"] }
