hello = "echo world"
py = { cmd = "print('Hello from Python!')", shell = "python -c" }
sequence = [
    "echo first",
    "echo second",
    "echo third"
]
advanced = { cmd = "echo 'Hello from Bash!'", shell = "bash -c" }
super_advanced = { cmd = [
    "echo first",
    "echo second",
    { cmd = [
        "echo parallel_one",
        "echo parallel_two",
        "echo parallel_three",
        { cmd = [
            "echo sequence_first",
            "echo sequence_second",
            "echo sequence_third"
        ] }
    ], parallel = true },
    "echo third"
] }
vars_test = { cmd = "echo %MY_VAR%", env = ["MY_VAR=YES"] }
vars_wont_work = { cmd = [
    "echo %MY_VAR%",
    "echo %MY_VAR%"
], env = ["MY_VAR='I am only defined on the parent, not in the child processes'"] }
vars_will_work = { cmd = [
    { cmd = "echo %MY_VAR%", env = ["MY_VAR=I am available now"] },
    { cmd = "echo %MY_VAR%", env = ["MY_VAR=And so am I"] },
] }
test_args = { cmd = "echo $ARG1 $ARG2", args = ["ARG1", "ARG2=Default value"] }
